spring:
  application:
    name: demo

  # 1. Configurações de Conexão com o Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  # 2. Configurações do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Tomar cuidado ao manter update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect